In [13]:
"Задание 1"

'Задание 1'

In [30]:
import pandas as pd

In [31]:
log=pd.read_csv('visit_log.csv', sep=';')
log.head()

,timestamp,visit_id,url,region,user_id,traffic_source
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex

In [32]:
def filtered(row):
    if row['traffic_source']=='yandex':
        return 'organic'
    elif row['traffic_source']=='google':
        return 'organic'
    elif row['traffic_source']=='paid':
        if row['region']=='Russia':
            return 'ad'
        else:
            return 'other'
    elif row['traffic_source']=='email':
        if row['region']=='Russia':
            return 'ad'
        else:
            return 'other'
    else:
        return row['traffic_source']

In [33]:
log['source_type']=log.apply(filtered, axis=1)

In [34]:
log.head(10)

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
5,1549980742,8855508aad,https://host.ru/df646c3676cc259fa0,Russia,fc43898e47,yandex,organic
6,1549980742,b0f66adc83,https://host.ru/b8b58337d272ee7b15,Russia,13fc55e781,paid,ad
7,1549980754,837885c8f8,https://host.ru/108ce4b365afb7b88e,Russia,cb5082b6f6,direct,direct
8,1549980760,af5570f5a1,https://host.ru/3004a8273caeef2867,China,45664f7af2,direct,direct
9,1549980765,3e7077fd2f,https://host.ru/df646c3676cc259fa0,Russia,6f9de8c8b6,email,ad

In [35]:
"Задание 2"

'Задание 2'

In [36]:
import pandas as pd
import re

In [37]:
urls=pd.read_csv('URLs.txt')

In [38]:
urls.head()

                                                 url
0                                            /world/
1                                           /latest/
2                                      /?updated=top
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...

In [39]:
urls[urls.url.str.contains('/[0-9]{8}-', regex=True)].head()

                                                 url
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...
5  /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6  /video/36001498-poyavilis-pervye-podrobnosti-g...
7  /world/36007585-tramp-pridumal-kak-reshit-ukra...

In [25]:
"Задание 3"

'Задание 3'

In [28]:
import pandas as pd

In [29]:
ratings = pd.read_csv('ratings.csv')
ratings

        userId  movieId  rating   timestamp
0            1       31     2.5  1260759144
1            1     1029     3.0  1260759179
2            1     1061     3.0  1260759182
3            1     1129     2.0  1260759185
4            1     1172     4.0  1260759205
...        ...      ...     ...         ...
99999      671     6268     2.5  1065579370
100000     671     6269     4.0  1065149201
100001     671     6365     4.0  1070940363
100002     671     6385     2.5  1070979663
100003     671     6565     3.5  1074784724

[100004 rows x 4 columns]

In [30]:
group_user = ratings.groupby('userId').agg({'userId':'count','timestamp':['min','max']})
group_user

       userId   timestamp
        count         min         max
userId
1          20  1260759108  1260759205
2          76   835355395   835356246
3          51  1298861589  1298932787
4         204   949778714   949982274
5         100  1163373044  1163375145
...       ...         ...         ...
667        68   847271220   847272234
668        20   993613196   993613478
669        37  1015829081  1015829766
670        31   938781328   940944033
671       115  1063500751  1074784735

[671 rows x 3 columns]

In [31]:
group_user.rename({'userId': 'activity', 'count': 'level'}, axis=1, inplace=True)
group_user

       activity   timestamp
          level         min         max
userId
1            20  1260759108  1260759205
2            76   835355395   835356246
3            51  1298861589  1298932787
4           204   949778714   949982274
5           100  1163373044  1163375145
...         ...         ...         ...
667          68   847271220   847272234
668          20   993613196   993613478
669          37  1015829081  1015829766
670          31   938781328   940944033
671         115  1063500751  1074784735

[671 rows x 3 columns]

In [32]:
active_user['LTV'].mean()

np.float64(40080507.4496124)

In [47]:
"Задание 4"

'Задание 4'

In [7]:
rzd = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115],
        'rzd_revenue': [1093, 2810, 10283, 5774, 981]
    }
)
rzd

   client_id  rzd_revenue
0        111         1093
1        112         2810
2        113        10283
3        114         5774
4        115          981

In [8]:
auto = pd.DataFrame(
    {
        'client_id': [113, 114, 115, 116, 117],
        'auto_revenue': [57483, 83, 912, 4834, 98]
    }
)
auto

   client_id  auto_revenue
0        113         57483
1        114            83
2        115           912
3        116          4834
4        117            98

In [9]:
air = pd.DataFrame(
    {
        'client_id': [115, 116, 117, 118],
        'air_revenue': [81, 4, 13, 173]
    }
)
air

   client_id  air_revenue
0        115           81
1        116            4
2        117           13
3        118          173

In [10]:
client_base = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115, 116, 117, 118],
        'address': ['Комсомольская 4', 'Энтузиастов 8а', 'Левобережная 1а', 'Мира 14', 'ЗЖБИиДК 1', 
                    'Строителей 18', 'Панфиловская 33', 'Мастеркова 4']
    }
)
client_base

   client_id          address
0        111  Комсомольская 4
1        112   Энтузиастов 8а
2        113  Левобережная 1а
3        114          Мира 14
4        115        ЗЖБИиДК 1
5        116    Строителей 18
6        117  Панфиловская 33
7        118     Мастеркова 4

In [11]:
rzd_auto = rzd.merge(auto, on='client_id', how='outer')
rzd_auto

   client_id  rzd_revenue  auto_revenue
0        111       1093.0           NaN
1        112       2810.0           NaN
2        113      10283.0       57483.0
3        114       5774.0          83.0
4        115        981.0         912.0
5        116          NaN        4834.0
6        117          NaN          98.0

In [12]:
rzd_auto_air = rzd_auto.merge(air, on='client_id', how='outer')
rzd_auto_air

   client_id  rzd_revenue  auto_revenue  air_revenue
0        111       1093.0           NaN          NaN
1        112       2810.0           NaN          NaN
2        113      10283.0       57483.0          NaN
3        114       5774.0          83.0          NaN
4        115        981.0         912.0         81.0
5        116          NaN        4834.0          4.0
6        117          NaN          98.0         13.0
7        118          NaN           NaN        173.0

In [13]:
all_info = rzd_auto_air.merge(client_base, on='client_id', how='outer')
all_info

   client_id  rzd_revenue  auto_revenue  air_revenue          address
0        111       1093.0           NaN          NaN  Комсомольская 4
1        112       2810.0           NaN          NaN   Энтузиастов 8а
2        113      10283.0       57483.0          NaN  Левобережная 1а
3        114       5774.0          83.0          NaN          Мира 14
4        115        981.0         912.0         81.0        ЗЖБИиДК 1
5        116          NaN        4834.0          4.0    Строителей 18
6        117          NaN          98.0         13.0  Панфиловская 33
7        118          NaN           NaN        173.0     Мастеркова 4